#!/bin/bash

# MedLink Claims Hub - CI Staging Setup Script
# This script generates the commands needed to set up CI for staging

STAGING_URL="https://med-link-claims-vlad218.replit.app"

echo "================================================"
echo "MedLink CI Staging Setup Instructions"
echo "================================================"
echo ""
echo "STAGING URL: $STAGING_URL"
echo ""
echo "Step 1: Set GitHub Secret"
echo "========================="
echo ""
echo "Go to your GitHub repository settings:"
echo "1. Navigate to Settings > Secrets and variables > Actions"
echo "2. Click 'New repository secret'"
echo "3. Name: STAGING_BASE_URL"
echo "4. Value: $STAGING_URL"
echo "5. Click 'Add secret'"
echo ""
echo "Step 2: Manually Dispatch Workflows"
echo "===================================="
echo ""
echo "After setting the secret, trigger each workflow manually:"
echo ""
echo "1. K6 Performance Testing:"
echo "   - Go to: Actions > Nightly Performance Testing"
echo "   - Click 'Run workflow'"
echo "   - Select 'staging' environment"
echo "   - Click 'Run workflow' (green button)"
echo ""
echo "2. ZAP Security Scanning:"
echo "   - Go to: Actions > Nightly Security Scanning"
echo "   - Click 'Run workflow'"
echo "   - Select 'staging' environment"
echo "   - Click 'Run workflow' (green button)"
echo ""
echo "3. Backup/Restore Validation:"
echo "   - Go to: Actions > Nightly Backup and Restore Validation"
echo "   - Click 'Run workflow'"
echo "   - Test mode: 'false'"
echo "   - Click 'Run workflow' (green button)"
echo ""
echo "Step 3: Collect Workflow URLs"
echo "=============================="
echo ""
echo "After triggering each workflow, collect the run URLs:"
echo "Format: https://github.com/[owner]/[repo]/actions/runs/[run-id]"
echo ""
echo "Step 4: Document Results"
echo "========================"
echo ""
echo "Once workflows complete, document in DAY0_REPORT.md:"
echo "- K6: p95 latency, error rate"
echo "- ZAP: vulnerability counts by severity"
echo "- Backup/Restore: RPO/RTO metrics"
echo ""
echo "================================================"
echo "CI Staging Setup Complete"
echo "================================================"